version: "2"

version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocyclo
    - gocognit
  settings:
    gocyclo:
      min-complexity: 26
    gocognit:
      min-complexity: 85

run:
  tests: true
